### ISSUE TITLE
[Improvement] Highlight box when event is onging

### ISSUE THREAD

**Issue by windhamwong** [duyluonglc/react-native-events-calendar#4]
This can be used with the redline.
When the current time is within the event date and time, the event box will be highlighted (blue colour). 
I am creating this issue instead of PR because this impacts some styles and behaviour. Please have a look.

Link: https://github.com/windhamwong/react-native-events-calendar/tree/pr/highlight

screenshot
![image](https://user-images.githubusercontent.com/677625/32577573-478ed704-c4d2-11e7-8eec-a84006f43bdb.png)

**Comment by duyluonglc** [comment]
@windhamwong thanks for your contribute
Should allow overwite `currentEventStyle` or turn on/off by `highlightCurrentEvents={true/false}` and add them to readme
